=== YIueil/yiueil-bdf/yl-bdf-web-query/src/main/resources/dynamicsql/yl-dynamic-sql.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT root (config)*><!--根节点-->
<!ATTLIST root
        cache (true|false) "false">

<!ELEMENT config (sql|params|filters|endSql)*><!--配置项-->
<!ATTLIST config
        id ID #REQUIRED
        description CDATA #IMPLIED>

<!ELEMENT sql (#PCDATA)>

<!ELEMENT params (param)*><!--内嵌参数列表-->
<!ELEMENT param (#PCDATA)>
<!ATTLIST param
        name CDATA #REQUIRED
        default CDATA #IMPLIED>

<!ELEMENT filters (filter)*><!--过滤参数列表-->
<!ELEMENT filter (#PCDATA)>
<!ATTLIST filter
        name CDATA #REQUIRED>
        left CDATA #IMPLIED>
        right CDATA #IMPLIED>
        type CDATA #IMPLIED>

<!ELEMENT endSql (#PCDATA)><!--尾接SQL-->

=== YIueil/yiueil-bdf/yl-bdf-web-search/src/main/resources/dynamicsql/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--使用dtd约束-->
<!--<!DOCTYPE root PUBLIC "yl-dynamic-sql.xsd" "https://yiueil.github.io/static-repo/static/dtd/yl-dynamic-sql.dtd">-->

<!--是应用xsd约束-->
<root cache="true"
      xmlns="http://www.yiueil.cn"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.yiueil.cn https://yiueil.github.io/static-repo/static/xsd/yl-dynamic-sql.xsd"
>
    <config id="getOrderList" >
        <sql><![CDATA[
                select * from order where 1 = 1 and id in (:ids)
        ]]></sql>
        <params>
            <param name="id"/>
        </params>
        <filters>
            <filter name="name"><![CDATA[
                and name = :name
            ]]>
            </filter>
        </filters>
        <endSql><![CDATA[
            order by id desc
        ]]></endSql>
    </config>
</root>

=== YIueil/yiueil-bdf/yl-bdf-web-query/src/main/resources/dynamicsql/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--使用dtd约束-->
<!--<!DOCTYPE root PUBLIC "yl-dynamic-sql.xsd" "https://yiueil.github.io/static-repo/static/dtd/yl-dynamic-sql.dtd">-->

<!--是应用xsd约束-->
<root cache="true"
      xmlns="http://www.yiueil.cn"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.yiueil.cn https://yiueil.github.io/static-repo/static/xsd/yl-dynamic-sql.xsd">
    <config id="exampleConfig">
        <sql><![CDATA[
            select * from table where 1 = 1 and id in (:ids)
        ]]></sql>
        <params>
            <param name="ids"/>
        </params>
        <filters>
            <filter name="guid"><![CDATA[
                and guid = :guid
            ]]></filter>
        </filters>
        <endSql><![CDATA[
            order by id desc
        ]]></endSql>
    </config>
</root>
